version: '3'
services:
  splash:
    restart: always
    image: scrapinghub/splash
    container_name: scrapy-splash
    ports:
      - "5023:5023"
      - "8050:8050"
      - "8051:8051"
  # python3:
  #   build:
  #     context: ./docker/python3
  #   container_name: python3
  #   depends_on:
  #     - splash
  #   tty: true
  mysql:
    build:
      context: ./docker/mysql
      args:
        - MYSQL_VERSION=5.7
    container_name: scrapy-mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - .data/data/mysql:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
